[variables]
NODE_VERSION = "18"
NPM_CONFIG_PRODUCTION = "true"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_PROGRESS = "false"
NPM_CONFIG_LOGLEVEL = "silent"

[phases.install]
cmds = [
  'npm install --production --no-audit --no-fund --no-optional --silent --prefer-offline'
]

[start]
cmd = 'npm start'