[variables]
NODE_VERSION = "18"
NPM_CONFIG_PRODUCTION = "true"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_FUND = "false"

[phases.install]
cmds = [
  'npm ci --production --no-audit --no-fund --quiet'
]

[start]
cmd = 'npm start'