[variables]
NODE_VERSION = "18"
NPM_CONFIG_PRODUCTION = "true"

[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.install]
cmds = [
  'npm config set fetch-timeout 300000',
  'npm config set fetch-retry-mintimeout 20000', 
  'npm config set fetch-retry-maxtimeout 120000',
  'npm ci --production --prefer-offline || npm install --production'
]

[start]
cmd = 'npm start'